dpe_project:
  target: ci
  outputs:
    ci:
      type: postgres
      host: localhost
      port: 5432
      user: dbt
      password: dbt
      dbname: dbt_ci
      schema: ci
      threads: 4