name: CI
on:
  pull_request:
    branches: [main]

jobs:
  dbt-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dbt_project
    env:
      DBT_PROFILES_DIR: ${{ github.workspace }}/ci
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: dbt
          POSTGRES_PASSWORD: dbt
          POSTGRES_DB: dbt_ci
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.12"
      - run: python -m pip install dbt-postgres
      - run: python -m dbt.cli.main --version
      - run: python -m dbt.cli.main deps
      - run: python -m dbt.cli.main debug
      - run: python -m dbt.cli.main build